name: Node.js CI

on: [push]

jobs:
  buildl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install &&  ./node_modules/.bin/quasar build -m electron -P always
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
  buildm:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install && ./node_modules/.bin/quasar build -m electron -P always
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
  buildw:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install && ./node_modules/.bin/quasar build -m electron -P always
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
